# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{t9n}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tanel Suurhans", "Tarmo Lehtpuu"]
  s.date = %q{2010-01-06}
  s.description = %q{A custom AR backend for I18n, translatable model columns and virtual attributes, languages database with integration and some utilities.}
  s.email = ["tanel.suurhans@perfectline.ee", "tarmo.lehtpuu@perfectline.ee"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.markdown",
     "generators/t9n/t9n_generator.rb",
     "generators/t9n/templates/initializer.rb",
     "generators/t9n/templates/language.rb",
     "generators/t9n/templates/migrations/create_languages.rb",
     "generators/t9n/templates/migrations/create_translations.rb",
     "generators/t9n/templates/translation.rb",
     "init.rb",
     "install.rb",
     "lib/t9n.rb",
     "lib/t9n/active_record/translatable_attribute.rb",
     "lib/t9n/backend/active_record.rb",
     "lib/t9n/backend/exception_handler.rb",
     "lib/t9n/backend/extension.rb",
     "lib/t9n/models/language.rb",
     "lib/t9n/models/translation.rb",
     "lib/t9n/util.rb",
     "lib/tasks/t9n.rake",
     "rails/init.rb"
  ]
  s.homepage = %q{http://perfectline.co.uk}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Translation package including I18n AR backend, translatable attributes and Language database by PerfectLine}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

